# Generated by Django 3.2.13 on 2022-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'Autodetect'), (1, 'Cisco IOS'), (2, 'Cisco IOS XE'), (3, 'Cisco IOS XR'), (4, 'Cisco ASA'), (5, 'Cisco NX OS'), (99, 'Unsupported')], default=0),
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
    ]
