# Generated by Django 3.2.13 on 2022-05-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220507_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'Autodetect'), (1, 'Cisco IOS'), (2, 'Cisco IOS XE'), (3, 'Cisco IOS XR'), (4, 'Cisco NX OS'), (5, 'Cisco ASA'), (99, 'Unsupported')], default=0),
        ),
    ]
